### ISSUE TITLE
 [Trello] Cuando caduca la pass, tras cambiarla, no se actualiza esta en BD. Tampoco se actualiza la última fecha de conexión 

### ISSUE THREAD

**Issue by miguelfito** [miguelfito/Manhattan#66]
Issue generada el 2014-03-09T09:23:16.282Z a partir de la card https://trello.com/c/jHfyhAte.

------------------------------------------------------------------

Cuando caduca la pass, tras cambiarla, no se actualiza esta en BD. Tampoco se actualiza la última fecha de conexión

------------------------------------------------------------------

**Comment by miguelfito** [comment]
Solved

**Comment by burlock** [comment]
Cerrando los Trello pendientes. Si señor!
